### PR TITLE
Fix stop deletion error

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

A recent merge caused the stop deletion error to be missing some required data. This PR reverts that.

### CODE REVIEW

**Review by daniel-heppner-ibigroup — APPROVED** [review]
great fix thank you!

**Review by br648 — APPROVED** [review]
Good spot! I'm not surprised it was in this class.

**Comment by vilmosnagy** [comment]
we've jut run into this issue. any chance this get merged (& updated in `datatools-server`) in the coming days? thanks.

**Comment by philip-cline** [comment]
Hi @vilmosnagy, we will bump the gtfs-lib version for datatools-server in a new PR shortly. That should provide you with the update.

**Pull request merged**
